releasenotes:
  sections:
  - title: "Feature Requests"
    emoji: ":pray:"
    labels: ["Feature Request", "new"]
  - title: "Enhancements"
    emoji: ":star:"
    labels: ["enhancement", "UI", "API"]
  - title: "Core Functionality"
    emoji: ":tada:"
    labels: ["Feature: 
    ", "Feature: Financial", "Feature: Groups", "Feature: Members", "Feature: Reports", "Feature: Sunday School", "Feature: Users", "Installation and Upgrade","Configuration","Data: Custom Field Promotion", "Feature: Data Import and Export","Feature: Emails","Feature: SMS","Feature: Social","Mobile"]  
  - title: "Localization"
    emoji: ":speech_balloon:"
    labels: ["Localization"]
  - title: "Bugs"
    emoji: ":beetle:"
    labels: ["bug", "P0 - Urgent"]
  - title: "Inner Beauty"
    emoji: ":gear:"
    labels: ["development","build", "Backend System", "Code Smell", "Package Dependencies"]
